const data= [
 {
    "name":"bulbasaur",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/bulbasaur.avif",
    "attack":"290",
    "defense":"89",
    "type":"electric",
    "experience":"167",
 },
 {
    "name":"ivysaur",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/ivysaur.avif",
    "attack":"125",
    "defense":"89",
    "type":"water",
    "experience":"99",
 },
 {
    "name":"venusaur",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/venusaur.avif",
    "attack":"54",
    "defense":"89",
    "type":"fire",
    "experience":"99",
 },
 {
     "name":"charmander",
     "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/charmander.avif",
     "attack":"54",
     "defense":"89",
     "type":"electric",
     "experience":"167",
     
 },
 {
    "name":"charmeleon",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/charmeleon.avif",
    "attack":"125",
    "defense":"89",
    "type":"water",
    "experience":"238",
 },
 {
    "name":"charizard",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/charizard.avif",
    "attack":"54",
    "defense":"89",
    "type":"fire",
    "experience":"99",
 },
 {
    "name":"squirtle",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/squirtle.avif",
    "attack":"290",
    "defense":"89",
    "type":"electric",
    "experience":"99",
 },
 {
    "name":"wartortle",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/wartortle.avif",
    "attack":"54",
    "defense":"89",
    "type":"water",
    "experience":"238",
 },
 {
    "name":"blastoise",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/blastoise.avif",
    "attack":"125",
    "defense":"89",
    "type":"fire",
    "experience":"99",
 },
 {
    "name":"caterpie",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/caterpie.avif",
    "attack":"54",
    "defense":"89",
    "type":"electric",
    "experience":"167",
 },
 {
    "name":"metapod",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/metapod.avif",
    "attack":"54",
    "defense":"89",
    "type":"water",
    "experience":"99",
 },
 {
    "name":"butterfree",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/butterfree.avif",
    "attack":"290",
    "defense":"89",
    "type":"fire",
    "experience":"238",
 },
 {
    "name":"weedle",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/weedle.avif",
    "attack":"125",
    "defense":"89",
    "type":"electric",
    "experience":"99",
 },
 {
    "name":"kakuna",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/kakuna.avif",
    "attack":"54",
    "defense":"89",
    "type":"water",
    "experience":"167",
 },
 {
    "name":"beedrill",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/beedrill.avif",
    "attack":"54",
    "defense":"89",
    "type":"fire",
    "experience":"99",
 },
 {
    "name":"pidgey",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/pidgey.avif",
    "attack":"125",
    "defense":"89",
    "type":"electric",
    "experience":"99",
 },
 {
    "name":"pidgeotto",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/pidgeotto.avif",
    "attack":"54",
    "defense":"89",
    "type":"water",
    "experience":"238",
 },
 {
    "name":"pidgeot",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/pidgeot.avif",
    "attack":"290",
    "defense":"89",
    "type":"fire",
    "experience":"167",
 },
 {
    "name":"rattata",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/rattata.avif",
    "attack":"54",
    "defense":"89",
    "type":"electric",
    "experience":"99",
 },
 {
    "name":"raticate",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/raticate.avif",
    "attack":"54",
    "defense":"89",
    "type":"water",
    "experience":"99",
 },
 {
    "name":"pikachu",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/pikachu.avif",
    "attack":"290",
    "defense":"89",
    "type":"fire",
    "experience":"99",
 },
 {
    "name":"spearow",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/spearow.avif",
    "attack":"125",
    "defense":"89",
    "type":"electric",
    "experience":"167",
 },
 {
    "name":"fearow",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/fearow.avif",
    "attack":"54",
    "defense":"89",
    "type":"water",
    "experience":"238",
 },
 {
    "name":"ekans",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/ekans.avif",
    "attack":"54",
    "defense":"89",
    "type":"fire",
    "experience":"99",
 },
 {
    "name":"rapidash",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/rapidash.avif",
    "attack":"54",
    "defense":"89",
    "type":"electric",
    "experience":"167",
 },
 {
    "name":"ditto",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/ditto.avif",
    "attack":"290",
    "defense":"89",
    "type":"water",
    "experience":"99",
 },
 {
    "name":"machamp",
    "img":" https://img.pokemondb.net/sprites/home/normal/2x/avif/machamp.avif",
    "attack":"125",
    "defense":"89",
    "type":"fire",
    "experience":"238",
 }
  ]
  export default data;